services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: algafood
        MYSQL_USER: algafood
        MYSQL_PASSWORD: test